### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by metaleap** [sourcegraph/go-diff#16]
Contains link that 404'd for me just now:

> https://sourcegraph.com/github.com/sourcegraph/go-diff/-/def/GoPackage/github.com/sourcegraph/go-diff/diff/-/FileDiff

Also still says:

> Unstable API: go-diff is currently in development

while last commit was ~10 months ago. Might wanna elaborate what can be unstable about it vs manually doing one's own `strings.Split(diffsrc, "\n")` then checking whether each line starts with a `+` or a `-`, a `+++` or `---`, or has 2x `@@` 😁

**Comment by sqs** [comment]
Thanks! Fixed. https://github.com/sourcegraph/go-diff/commit/748a069ce7626ea59d76c3b5786b4281b7cfc98d
