### ISSUE TITLE
Need an option to keep no newline message

### ISSUE THREAD

**Issue by tengattack** [sourcegraph/go-diff#20]
Hi, I'm developing a GitHub CI program by using this package.

However, I faced this problem: I can't calculate the position precisely when the original source file has no newline in the end. The position parameter is defined in [here](https://developer.github.com/v3/pulls/comments/#create-a-comment).

```diff
diff --git a/foo.php b/foo.php
index 88f2483c..b58d7b34 100644
--- a/foo.php
+++ b/foo.php
@@ -1,6 +1,4 @@
-<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
+<?xml version="1.0" encoding="UTF-8"?>
 <i>
-    <?php
-    echo $dm->text;
-    ?>
-</i>
\ No newline at end of file
+    <d p="<?= $dm->p ?>"><?= \yii\bootstrap\Html::encode($dm->text) ?></d>
+</i>
```

In the `hunk.Body` we has no `\ No newline at end of file` message so that I couldn't figure out the right position for the new lines after that message.

**Comment by shurcooL** [comment]
Can you check if the [`Hunk.OrigNoNewlineAt`](https://godoc.org/sourcegraph.com/sourcegraph/go-diff/diff#Hunk.OrigNoNewlineAt) field tracks the information you need?

https://github.com/sourcegraph/go-diff/blob/3f415a150aec0685cb81b73cc201e762e075006d/diff/diff.pb.go#L64-L65

**Comment by tengattack** [comment]
Oh Thanks! It works.
