### ISSUE TITLE
tag the code with v1.0.0 (or v0.0.1 etc.)

### ISSUE THREAD

**Issue by dmitris** [sourcegraph/go-diff#24]
@keegancsmith - would you consider tagging the code with `v1.0.0` (or `v0.5.0` if you prefer)? If you create a release, it will automatically tag the code.  It will make using your (very helpful!) library somewhat easier to use with Go modules.  Thanks.

**Comment by keegancsmith** [comment]
Done https://github.com/sourcegraph/go-diff/releases/tag/v0.5.0

**Comment by dmitris** [comment]
thanks
