### ISSUE TITLE
Passthrough for non-diff output

### ISSUE THREAD

**Issue by craigfurman** [sourcegraph/go-diff#59]
I've recently started using this library, to redact diffs that pertain to secret files from logs. It would be great if (Multi)FileDiffReader could yield content that is not part of a valid diff, so that the caller has the choice of whether or not to print it.

For example, the program `colordiff` will successfully print non-diff output, allowing it to be used to process input that is mixed diff and non-diff content.

What do you think of this feature, and would you be interested in a PR that implements it?

**Comment by keegancsmith** [comment]
cc @mrnugget @eseliger

**Comment by mrnugget** [comment]
That sounds reasonable - if the implemenation doesn't become convoluted, I think we'd accept a PR, yes :)

**Comment by craigfurman** [comment]
OK, I've had a go at it here: https://github.com/sourcegraph/go-diff/pull/60

let me know what you think 🙂
